language: python
python:
  - "3.6"

sudo: false

install:
  - "pip install sphinx"
  - "pip install hyperspy"
  - "pip install pymatgen"
  - "pip install Cython"
  - "python setup.py install"
script:
  - pytest tests/test_diffraction_signal.py  # until more tests implemented
  - sphinx-build -b html docs/source docs/build

deploy:
  provider: pages
  skip_cleaup: true
  github_token: $GITHUB_TOKEN
  local_dir: ${TRAVIS_BUILD_DIR}/docs/build/html
  on:
    branch: continuous-integration
